version: "3.8"

services:
    gateway:
      build:
        context: ./gateway
      command: npm start
      ports:
        - 3000:3000
      depends_on:
        - db
      volumes:
        - ./gateway:/user/gateway
      links:
        - db

    api:
      build: 
        context: ./api
      command: npm start
      ports:
        - 3001:3001
      depends_on:
        - db
      volumes:
        - ./api:/user/api
      links:
        - db

    ws:
      build:
        context: ./ws
      command: npm start
      ports:
        - 3002:3002
      depends_on:
        - db
      volumes:
        - ./ws:/user/ws
      links:
        - db

    db:
      image: mongo
      restart: unless-stopped
      ports:
        - 27017:27017
      volumes:
        - db:/data/db

    postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "root"
      ports:
      - "5432:5432"
  
volumes:
  db: