version: '3.8'
services:

  dbtask: 
    image: mongo
    container_name: dbapp
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:prod
      - MONGO_INITDB_ROOT_PASSWORD:bBsAQDnZxx6xC
    ports:
      - 27016:27017 
      - 28016:28017 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge